### ISSUE TITLE
Evaluation?

### ISSUE THREAD

**Issue by debayan** [sunnysai12345/KVMemnn#1]
Hi,

I wanted to know if your implementation evaluation accuracy is close to that of the original paper or not. In my observation of running examples.py I see that the output is not very good. Can you confirm that the code is correctly implemented?
Also, where is the pre-trained model file?

**Comment by WindHunter-Yang** [comment]
How to solve this problem?  Can you help me?

**Comment by WindHunter-Yang** [comment]
I also don't know how to evalute the model
